{% set name = "aixd" %}
{% set version = "0.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aixd-{{ version }}.tar.gz
  sha256: 00cd142dfb5e1cd4c072f9a2db9f3037a2ccbcdda298b19d55145ee5a78e5621

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pandas >=2.1.0
    - numpy >=1.22.4
    - scipy >=1.8.1
    - scikit-learn >=0.23.0
    - plotly ~=6.0.0
    - pytorch >=2.0.0
    - wandb
    - pytorch-lightning >=2.0.0
    - bayesian-optimization <2.0.0
    - coolname
    - python >={{ python_min }}
    
test:
  imports:
    - aixd
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aixd.ethz.ch/
  summary: 'AIXD is your go-to toolkit for design evaluation, generation, exploration, and optimization, seamlessly blending parametric modeling with AI capabilities'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gonzalocasas
    - amaissen
